version: "3.9"
services:
  web:
    build: .
    environment:
      APP_DBPASSWORD: "test"  
    ports:
      - "8000:8000"
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: secret

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080